'use strict';
const $=s=>document.querySelector(s), $$=s=>[...document.querySelectorAll(s)];
let rightColor=0,toggleRevision=-1,togglePixels=new Map();
let state, catalog, token, selected, frame=0, color=7, tool='pencil', zoom=16, palettePage=0, pending=false, drawing=null, report=null, playTimer=null, referenceImage=null, referenceKey='', toastTimer, validationSerial=0;
const canvas=$('#editor'), ctx=canvas.getContext('2d');
let regionClipboard=null,paletteEditIndex=0,stamp=null,tileDrag=null;
function view(){const a=asset(),tw=mode().encoding==='text'?6:8;const enabled=$('#tileFocus').checked&&mode().kind==='character';const cols=Math.ceil(a.width/tw),total=cols*Math.ceil(a.height/8);const ti=Math.max(0,Math.min(total-1,+$('#tileNumber').value||0));$('#tileNumber').value=ti;$('#tileNumber').max=total-1;$('#tileTotal').textContent='/ '+(total-1);$('#tileFocus').disabled=mode().kind!=='character';for(const id of ['tileNumber','prevTile','nextTile'])$('#'+id).disabled=mode().kind!=='character';const n=+$('#editSize').value/8,w=Math.min(a.width,tw*n),h=Math.min(a.height,8*n);return enabled?{x:Math.min(ti%cols*tw,a.width-w),y:Math.min(Math.floor(ti/cols)*8,a.height-h),width:w,height:h}:{x:0,y:0,width:a.width,height:a.height}}
function fitCanvas(){if($('#tileFocus').checked&&mode().kind==='character'){zoom=512/(+$('#editSize').value);draw();return}const v=view(),width=$('.editing-view').clientWidth-276,height=Math.max(256,Math.min(568,window.innerHeight-$('#canvasWrap').getBoundingClientRect().top-212));zoom=[64,48,32,24,16,12,8,4,2,1].find(z=>v.width*z<=width&&v.height*z<=height)||1;$('#zoom').value=zoom;draw()}

function visibleAssets(){return state.project.assets.filter(a=>a.chip==='TMS9918A')}
function asset(){return state?.project.assets.find(a=>a.id===selected)}
function mode(){return catalog.modes.find(m=>m.id===asset().mode)}
function direct(){return ['rgb15','yjk','yjae','yuv','yuae'].includes(mode().encoding)}
function rgbHex(p){return '#'+[((p>>5)&31),(p>>10)&31,p&31].map(v=>Math.round(v*255/31).toString(16).padStart(2,'0')).join('')}
function to15(hex){const [r,g,b]=[1,3,5].map(i=>Math.round(parseInt(hex.slice(i,i+2),16)*31/255));return (g<<10)|(r<<5)|b}
function pixelHex(a,p){return ['rgb15','yjk','yjae','yuv','yuae'].includes(catalog.modes.find(m=>m.id===a.mode).encoding)?rgbHex(p):a.palette[p]}
function notify(message,error=false){clearTimeout(toastTimer);$('#toast').textContent=message;$('#toast').classList.toggle('error',error);$('#toast').hidden=false;toastTimer=setTimeout(()=>$('#toast').hidden=true,error?9000:3500)}
async function api(path,body){const r=await fetch(path,body?{method:'POST',headers:{'Content-Type':'application/json','X-Studio-Token':token},body:JSON.stringify(body)}:undefined);if(!r.ok){let e;try{e=await r.json()}catch{e={error:r.statusText}}const err=new Error(e.error||r.statusText);err.status=r.status;throw err}return r.json()}
function download(data,name,type='application/json'){const url=URL.createObjectURL(new Blob([data],{type}));const a=document.createElement('a');a.href=url;a.download=name;a.click();setTimeout(()=>URL.revokeObjectURL(url),2000)}
async function mutate(body){if(pending||drawing)return false;stopPlay();pending=true;document.body.classList.add('busy');$('#saveStatus').textContent='保存中…';const recovery=JSON.stringify(state.project);try{const r=await api('/api/mutate',{baseRevision:state.revision,assetId:selected,frame,...body});state=r;if(r.assetId)selected=r.assetId;render();return true}catch(e){if(e.status===409){download(recovery,'conflict-recovery.msxpix.json');state=await api('/api/state');render();notify('他の編集と競合しました。未保存の内容をrecoveryファイルに退避し、最新の状態を表示しました。',true)}else{state=await api('/api/state');render();notify(e.message,true)}return false}finally{pending=false;document.body.classList.remove('busy')}}
function paintTo(target,a,fi){target.width=a.width;target.height=a.height;const c=target.getContext('2d');const img=c.createImageData(a.width,a.height);const am=catalog.modes.find(m=>m.id===a.mode),sprite=am.kind==='sprite',ad=['rgb15','yjk','yjae','yuv','yuae'].includes(am.encoding);a.frames[fi].pixels.forEach((p,i)=>{const hex=ad?rgbHex(p):a.palette[p];img.data[i*4]=parseInt(hex.slice(1,3),16);img.data[i*4+1]=parseInt(hex.slice(3,5),16);img.data[i*4+2]=parseInt(hex.slice(5,7),16);img.data[i*4+3]=sprite&&p===0?0:255});c.putImageData(img,0,0)}
function thumb(a,fi=0){const c=document.createElement('canvas');paintTo(c,a,fi);return c}
function render(){$('#outputText').value='';const available=visibleAssets();const hiddenCount=state.project.assets.length-available.length;$('#archivedAssetsNote').hidden=!hiddenCount;$('#archivedAssetsNote').textContent=hiddenCount+'件の他VDP素材はプロジェクト内に保持';$('.workspace').hidden=!available.length;$('#emptyWorkspace').hidden=!!available.length;$('#assetCount').textContent=available.length;$('#partsLibrary').hidden=!available.length;$('#exportTop').disabled=!available.length;$('#duplicateAsset').disabled=!available.length;$('#deleteAsset').disabled=!available.length;if(!available.length){selected=null;$('#assets').replaceChildren();$('#connection').textContent='ローカル保存 · MCP対応';return}if(!available.some(a=>a.id===selected)){selected=available[0].id;frame=0;$('#tileNumber').value=0;$('#tileFocus').checked=true}const a=asset();frame=Math.min(frame,a.frames.length-1);if(!direct())color=Math.min(color,a.palette.length-1);$('#assetName').value=a.name;$('#assetKind').textContent=mode().kind.toUpperCase();$('#assetMeta').textContent=`${mode().label}  ·  ${a.width} × ${a.height}`;$('#assetCount').textContent=String(available.length);$('#revision').textContent='rev '+state.revision;$('#saveStatus').textContent='● 自動保存済み';$('#connection').textContent='ローカル保存 · MCP対応';$('#undo').disabled=!state.undo;$('#redo').disabled=!state.redo;$('#notes').value=a.notes||'';$('#modeNote').textContent=mode().note;$('#assets').replaceChildren();for(const x of available){const b=document.createElement('button');b.className='asset'+(x.id===selected?' active':'');b.dataset.assetId=x.id;b.append(thumb(x));const text=document.createElement('span'),title=document.createElement('b'),meta=document.createElement('small');title.textContent=x.name;meta.textContent=`${catalog.modes.find(m=>m.id===x.mode).label} · ${x.width}×${x.height}`;text.append(title,meta);b.append(text);b.onclick=()=>selectAsset(x.id);$('#assets').append(b)}renderPalette();renderFrames();renderReference();renderActivity();draw();validate()}
function selectAsset(id){if(drawing||pending||!visibleAssets().some(a=>a.id===id))return;stopPlay();selected=id;frame=0;palettePage=0;referenceKey='';report=null;$('#cursor').textContent='X —  Y —';$('#tileInfo').textContent='TILE —';$('#tileFocus').checked=false;$('#tileNumber').value=0;render();fitCanvas()}
function renderPalette(){const a=asset();const isdirect=direct();palettePage=Math.min(palettePage,Math.ceil(a.palette.length/64)-1);$('#palette').replaceChildren();const start=palettePage*64;for(let i=start;i<Math.min(start+64,a.palette.length);i++){const b=document.createElement('button');b.className='swatch'+(!isdirect&&i===color?' active':'')+(i===0?' zero':'');b.style.background=a.palette[i];b.title=`色 ${i} · ${a.palette[i]}`;b.setAttribute('aria-label',`色 ${i} ${a.palette[i]}`);b.onclick=()=>{color=isdirect?to15(a.palette[i]):i;renderPalette()};b.oncontextmenu=e=>{e.preventDefault();if($('#inputMode').value==='dual'){rightColor=isdirect?to15(a.palette[i]):i;renderPalette()}};b.ondblclick=()=>{if(a.chip==='TMS9918A'||mode().encoding==='grb8')return;paletteEditIndex=i;$('#paletteEdit').value=a.palette[i];$('#paletteEdit').click()};$('#palette').append(b)}rightColor=Math.min(rightColor,a.palette.length-1);$('.canvas-hint').textContent=$('#inputMode').value==='simple'?'左クリックで描画 · 右クリックで消去 · Iでスポイト':$('#inputMode').value==='multi'?'鉛筆：左で描画／再クリックで復元 · 右でスポイト':'鉛筆：左右の色で描画／同じボタンの再クリックで復元';saveEditorPreferences();$('#rightColorInfo').hidden=$('#inputMode').value!=='dual';$('#rightColorInfo').textContent='右クリック色：#'+rightColor+'（パレットを右クリックで選択）';$('#palettePage').textContent=`${start}–${Math.min(start+63,a.palette.length-1)}`;$('#prevPalette').disabled=palettePage===0;$('#nextPalette').disabled=start+64>=a.palette.length;const hex=isdirect?rgbHex(color):a.palette[color];$('#colorSwatch').style.background=hex;$('#colorHex').textContent=hex.toUpperCase();$('#colorIndex').textContent=isdirect?`GRB555 ${color}`:'#'+color.toString(16).padStart(2,'0').toUpperCase();$('#paletteNote').textContent=isdirect?'直接色 / RGB555':a.chip==='TMS9918A'||mode().encoding==='grb8'?'固定パレット':a.chip==='V9968'||a.chip==='V9990'?'編集可能 / RGB555':'編集可能 / RGB333';$('#colorInput').value=hex;$('#colorInput').disabled=!isdirect&&(a.chip==='TMS9918A'||mode().encoding==='grb8')}
function renderFrames(){$('#frames').replaceChildren();const a=asset();$('#frameCount').textContent=`${frame+1} / ${a.frames.length}`;a.frames.forEach((f,i)=>{const b=document.createElement('button');b.className='frame'+(i===frame?' active':'');b.setAttribute('aria-label',`フレーム ${i+1}`);b.append(thumb(a,i));const s=document.createElement('small');s.textContent=String(i+1).padStart(2,'0');b.append(s);b.onclick=()=>{if(pending||drawing)return;stopPlay();frame=i;$('#outputText').value='';renderFrames();draw()};$('#frames').append(b)});$('#duration').value=a.frames[frame].duration;$('#deleteFrame').disabled=a.frames.length===1}
function renderReference(){const r=asset().reference;$('#referenceControls').hidden=!r;if(r){$('#refOpacity').value=r.opacity*100;$('#refX').value=r.x;$('#refY').value=r.y;$('#refW').value=r.width;$('#refH').value=r.height;if(referenceKey!==r.data){referenceKey=r.data;referenceImage=new Image();referenceImage.onload=draw;referenceImage.src=r.data}}else{referenceImage=null;referenceKey=''}}
function draw(){if(!asset())return;const a=asset();const v=view();zoom=[64,48,32,24,16,12,8,4,2,1].find(z=>z<=zoom&&v.width*z<=8192&&v.height*z<=8192&&v.width*v.height*z*z<=16777216)||1;$('#zoom').value=zoom;const cw=v.width*zoom,ch=v.height*zoom;if(canvas.width!==cw||canvas.height!==ch){canvas.width=cw;canvas.height=ch}ctx.imageSmoothingEnabled=false;ctx.clearRect(0,0,cw,ch);ctx.fillStyle='#10141b';ctx.fillRect(0,0,cw,ch);if(mode().kind==='sprite'){for(let y=0;y<ch;y+=8)for(let x=0;x<cw;x+=8){ctx.fillStyle=((x+y)/8)%2?'#303943':'#18212a';ctx.fillRect(x,y,8,8)}}const off=thumb(a,frame);ctx.drawImage(off,v.x,v.y,v.width,v.height,0,0,cw,ch);if($('#onion').checked&&frame>0){ctx.globalAlpha=.22;ctx.drawImage(thumb(a,frame-1),v.x,v.y,v.width,v.height,0,0,cw,ch);ctx.globalAlpha=1}if($('#grid').checked&&(zoom>=4||$('#stampActive').checked)){ctx.lineWidth=1;ctx.beginPath();ctx.strokeStyle='#b0c0d018';for(let x=0;x<=v.width;x++){ctx.moveTo(x*zoom+.5,0);ctx.lineTo(x*zoom+.5,ch)}for(let y=0;y<=v.height;y++){ctx.moveTo(0,y*zoom+.5);ctx.lineTo(cw,y*zoom+.5)}ctx.stroke();ctx.beginPath();ctx.strokeStyle='#a8bcd84d';const tw=mode().encoding==='text'?6:['yjk','yjae','yuv','yuae'].includes(mode().encoding)?4:mode().kind==='character'?8:v.width;for(let x=0;x<=v.width;x+=tw){ctx.moveTo(x*zoom+.5,0);ctx.lineTo(x*zoom+.5,ch)}for(let y=0;y<=v.height;y+=(mode().kind==='character'?8:v.height)){ctx.moveTo(0,y*zoom+.5);ctx.lineTo(cw,y*zoom+.5)}ctx.stroke()}if(report&&!drawing){ctx.strokeStyle='#ff7865';ctx.lineWidth=2;for(const bad of report.violations.filter(b=>b.frame===frame)){ctx.strokeRect((bad.x-v.x)*zoom+1,(bad.y-v.y)*zoom+1,Math.min(8,a.width-bad.x)*zoom-2,zoom-2)}}paintTo($('#preview'),a,frame);drawOverviewReference(a);overviewLayout()}
async function validate(){const id=selected,serial=++validationSerial;try{const r=await api('/api/validate?asset='+id);if(id!==selected||serial!==validationSerial)return;report=r;$('#outputPanel').classList.toggle('has-errors',!r.valid);$('#outputPanel > summary').textContent=r.valid?'色の確認・書き出し・AI・編集ログ':'色の確認（制約超過あり）・書き出し・AI・編集ログ';const el=$('#validation');el.classList.toggle('bad',!r.valid);el.replaceChildren(document.createTextNode(r.valid?'✓ すべてのフレームが色数制約を満たしています':`! ${r.violationCount}箇所で色数制約を超えています`));for(const v of r.violations.slice(0,8)){const b=document.createElement('button');b.className='violation';b.textContent=`F${v.frame+1} (${v.x},${v.y}) ${v.message}`;b.onclick=()=>{frame=v.frame;renderFrames();draw();$('#canvasWrap').scrollTo({left:Math.max(0,v.x*zoom-100),top:Math.max(0,v.y*zoom-100)})};el.append(b)}const small=document.createElement('small');small.textContent=r.warnings.join(' ')||(r.valid?'バイナリ出力可能 · 原画データの検証（実機動作検証ではありません）':'バイナリ出力前に色制約を修正してください。PNG・プロジェクト保存は可能です。');el.append(small);draw()}catch(e){notify(e.message,true)}}
function renderActivity(){$('#activity').replaceChildren();for(const e of [...state.events].reverse()){const d=document.createElement('div');d.textContent=`${e.time}  r${String(e.revision).padStart(3,'0')}  ${e.source.padEnd(3)}  ${e.action}`;$('#activity').append(d)}if(!state.events.length)$('#activity').textContent='編集操作はここに記録されます。UI / MCP のどちらの操作か確認できます。'}
function coords(e){const r=canvas.getBoundingClientRect(),v=view();return{x:v.x+Math.max(0,Math.min(v.width-1,Math.floor((e.clientX-r.left)/zoom))),y:v.y+Math.max(0,Math.min(v.height-1,Math.floor((e.clientY-r.top)/zoom)))}}
function line(x0,y0,x1,y1,put){let dx=Math.abs(x1-x0),sx=x0<x1?1:-1,dy=-Math.abs(y1-y0),sy=y0<y1?1:-1,err=dx+dy;for(;;){put(x0,y0);if(x0===x1&&y0===y1)break;const e=2*err;if(e>=dy){err+=dy;x0+=sx}if(e<=dx){err+=dx;y0+=sy}}}
function flood(x,y,value){const a=asset(),p=a.frames[frame].pixels,w=a.width,h=a.height,v=view(),old=p[y*w+x];if(old===value)return;const stack=[y*w+x];p[y*w+x]=value;while(stack.length){const i=stack.pop(),xx=i%w,yy=Math.floor(i/w);for(const n of [xx>v.x?i-1:-1,xx<v.x+v.width-1?i+1:-1,yy>v.y?i-w:-1,yy<v.y+v.height-1?i+w:-1])if(n>=0&&p[n]===old){p[n]=value;stack.push(n)}}}
function drawGesture(pos){const a=asset();let p=a.frames[frame].pixels;const d=drawing;const put=(x,y)=>{const i=y*a.width+x;if(d.toggle){if(d.visited.has(i))return;d.visited.add(i);const key=selected+':'+frame+':'+i,old=togglePixels.get(key);if(old&&old.after===p[i]&&old.button===d.button){p[i]=old.before;togglePixels.delete(key)}else{togglePixels.set(key,{before:p[i],after:d.color,button:d.button});p[i]=d.color}}else p[i]=d.color};if(tool==='line'||tool==='rect'){p=a.frames[frame].pixels=[...d.before];if(tool==='line')line(d.start.x,d.start.y,pos.x,pos.y,put);else{line(d.start.x,d.start.y,pos.x,d.start.y,put);line(pos.x,d.start.y,pos.x,pos.y,put);line(pos.x,pos.y,d.start.x,pos.y,put);line(d.start.x,pos.y,d.start.x,d.start.y,put)}}else if(tool==='pencil'||tool==='eraser')line(d.last.x,d.last.y,pos.x,pos.y,put);d.last=pos;draw()}
canvas.addEventListener('contextmenu',e=>e.preventDefault());
canvas.addEventListener('pointerdown',e=>{if(pending||drawing||![0,2].includes(e.button))return;e.preventDefault();stopPlay();const pos=coords(e),a=asset();if($('#stampActive').checked){placeStamp(pos,e.button===2);return}if(($('#inputMode').value==='multi'&&e.button===2)||(tool==='picker'&&e.button!==2)){togglePixels.clear();color=a.frames[frame].pixels[pos.y*a.width+pos.x];if(!direct())palettePage=Math.floor(color/64);renderPalette();return}if(toggleRevision!==state.revision){togglePixels.clear();toggleRevision=state.revision}canvas.setPointerCapture(e.pointerId);drawing={id:e.pointerId,before:[...a.frames[frame].pixels],start:pos,last:pos,color:tool==='eraser'?0:e.button===2?($('#inputMode').value==='dual'?rightColor:0):color,toggle:tool==='pencil'&&$('#inputMode').value!=='simple',button:e.button,visited:new Set(),toggleBefore:new Map(togglePixels)};$('#saveStatus').textContent='編集中…';if(tool==='fill'){flood(pos.x,pos.y,drawing.color);draw()}else drawGesture(pos)});
canvas.addEventListener('pointermove',e=>{const p=coords(e),a=asset();$('#cursor').textContent=`X ${String(p.x).padStart(3)}   Y ${String(p.y).padStart(3)}`;const tw=mode().encoding==='text'?6:8;const ti=Math.floor(p.y/8)*Math.ceil(a.width/tw)+Math.floor(p.x/tw);$('#tileInfo').textContent=`TILE ${ti} ($${ti.toString(16).toUpperCase()})`;if(drawing&&e.pointerId===drawing.id)drawGesture(p)});
async function finish(e,cancel=false){if(!drawing||drawing.id!==e.pointerId)return;const d=drawing;drawing=null;if(canvas.hasPointerCapture(e.pointerId))canvas.releasePointerCapture(e.pointerId);if(cancel){togglePixels=d.toggleBefore;asset().frames[frame].pixels=d.before;draw();$('#saveStatus').textContent='操作を取消';return}if(await mutate({action:'frame_pixels',pixels:asset().frames[frame].pixels})){if(!d.toggle)togglePixels.clear();toggleRevision=state.revision}else togglePixels.clear()}
canvas.addEventListener('pointerup',e=>finish(e));canvas.addEventListener('pointercancel',e=>finish(e,true));
$('#inputMode').onchange=()=>{togglePixels.clear();renderPalette();$('.canvas-hint').textContent=$('#inputMode').value==='simple'?'左クリックで描画 · 右クリックで消去 · Iでスポイト':$('#inputMode').value==='multi'?'鉛筆：左で描画／再クリックで復元 · 右でスポイト':'鉛筆：左右の色で描画／同じボタンの再クリックで復元'};
function setTool(t){tool=t;$$('[data-tool]').forEach(b=>b.classList.toggle('active',b.dataset.tool===t))}
$$('[data-tool]').forEach(b=>b.onclick=()=>setTool(b.dataset.tool));$('#editSize').onchange=()=>{$('#tileFocus').checked=true;$('#stampActive').checked=false;modeWorkspace();fitCanvas()};$('#zoom').onchange=()=>{zoom=+$('#zoom').value;draw()};$('#fit').onclick=fitCanvas;$('#grid').onchange=draw;$('#onion').onchange=draw;
$('#undo').onclick=()=>mutate({action:'undo'});$('#redo').onclick=()=>mutate({action:'redo'});$$('[data-transform]').forEach(b=>b.onclick=()=>mutate({action:'transform',operation:b.dataset.transform,...view()}));$('#constrain').onclick=()=>mutate({action:'constrain'});$('#assetName').onchange=()=>mutate({action:'metadata',name:$('#assetName').value});$('#notes').onchange=()=>mutate({action:'metadata',notes:$('#notes').value});$('#duplicateAsset').onclick=()=>mutate({action:'duplicate'});$('#deleteAsset').onclick=()=>{if(confirm('この素材を削除しますか？「戻す」で取り消せます。'))mutate({action:'delete'})};
$('#addFrame').onclick=async()=>{if(await mutate({action:'add_frame',duplicate:true})){frame++;renderFrames();draw()}};$('#blankFrame').onclick=async()=>{if(await mutate({action:'add_frame',duplicate:false})){frame++;renderFrames();draw()}};$('#deleteFrame').onclick=()=>mutate({action:'delete_frame'});$('#duration').onchange=()=>mutate({action:'duration',duration:+$('#duration').value});
function stopPlay(){clearTimeout(playTimer);playTimer=null;$('#play').textContent='▶ 再生'}
$('#play').onclick=()=>{if(playTimer){stopPlay();return}$('#play').textContent='■ 停止';const step=()=>{frame=(frame+1)%asset().frames.length;renderFrames();draw();playTimer=setTimeout(step,asset().frames[frame].duration)};playTimer=setTimeout(step,asset().frames[frame].duration)};
$('#prevPalette').onclick=()=>{palettePage--;renderPalette()};$('#nextPalette').onclick=()=>{palettePage++;renderPalette()};$('#colorInput').onchange=()=>{if(direct()){color=to15($('#colorInput').value);renderPalette();return}const a=asset(),bits=['V9968','V9990'].includes(a.chip)?31:7;const hex='#'+[1,3,5].map(i=>Math.round(Math.round(parseInt($('#colorInput').value.slice(i,i+2),16)*bits/255)*255/bits).toString(16).padStart(2,'0')).join('');const palette=[...a.palette];palette[color]=hex;mutate({action:'metadata',palette})};
function binaryPixels(data,threshold){
 for(let i=0;i<data.length;i+=4){if(data[i+3]<128)continue;const value=(299*data[i]+587*data[i+1]+114*data[i+2])>=threshold*1000?255:0;data[i]=data[i+1]=data[i+2]=value;}
 return data;
}
async function binaryImage(data,width,height,threshold){
 const image=new Image();await new Promise((resolve,reject)=>{image.onload=resolve;image.onerror=()=>reject(new Error('画像を読み込めません'));image.src=data});
 if(image.width*image.height>16000000)throw new Error('画像は1600万画素以下にしてください');
 const c=document.createElement('canvas');c.width=width;c.height=height;const context=c.getContext('2d');
 const ratio=Math.min(width/image.width,height/image.height,1),w=Math.max(1,Math.round(image.width*ratio)),h=Math.max(1,Math.round(image.height*ratio));
 context.drawImage(image,Math.floor((width-w)/2),Math.floor((height-h)/2),w,h);
 const pixels=context.getImageData(0,0,width,height);binaryPixels(pixels.data,threshold);context.putImageData(pixels,0,0);return c.toDataURL('image/png');
}
let importDraft=null,importResult=null;
function cancelImageImport(){importDraft=null;importResult=null;$('#importPreviewPanel').hidden=true;$('#imageFile').value=''}
function quantizeImport(a,m,rgba,dither){
 const pal=a.palette.map(h=>[1,3,5].map(i=>parseInt(h.slice(i,i+2),16))),sprite=m.kind==='sprite';
 const near=(c,ids)=>ids.reduce((best,id)=>{const dist=j=>pal[j].reduce((n,v,k)=>n+(v-c[k])**2,0);return dist(id)<dist(best)?id:best},ids[0]);
 const ids=pal.map((_,i)=>i).filter(i=>!sprite||i>0),p=[];
 for(let i=0;i<a.width*a.height;i++){if(rgba[i*4+3]<128){p.push(0);continue}const delta=dither?[-8,0,-6,2,4,-4,6,-2,-5,3,-7,1,7,-1,5,-3][(Math.floor(i/a.width)%4)*4+i%a.width%4]*3:0;p.push(near([0,1,2].map(k=>Math.max(0,Math.min(255,rgba[i*4+k]+delta))),ids))}
 const temp={...a,frames:[{pixels:p}]},tw=m.encoding==='text'?6:8,tiles=a.width/tw*a.height/8,step=m.encoding==='g1'?8:1;
 const count=['text','sp1'].includes(m.encoding)?1:tiles;
 for(let t=0;t<count;t+=step)for(const g of colorGroups(temp,m,t,0)){const freq=new Map();for(const i of g.indices){if(sprite&&p[i]===0)continue;freq.set(p[i],(freq.get(p[i])||0)+1)}const keep=[...freq].sort((a,b)=>b[1]-a[1]).slice(0,sprite?1:2).map(v=>v[0]);for(const i of g.indices)if(keep.length&&!(sprite&&p[i]===0)&&!keep.includes(p[i]))p[i]=near(pal[p[i]],keep)}
 return p;
}
function updateImportPreview(){
 const kind=$('#imageImportMode').value;$('#binaryOptions').hidden=kind!=='binary';$('#dither').disabled=kind!=='color';
 if(!importDraft)return;
 const a=importDraft.asset,img=importDraft.image,c=document.createElement('canvas');c.width=a.width;c.height=a.height;const ctx=c.getContext('2d'),ratio=Math.min(a.width/img.width,a.height/img.height)*(+$('#importScale').value/100),w=Math.max(1,Math.round(img.width*ratio)),h=Math.max(1,Math.round(img.height*ratio));ctx.drawImage(img,Math.floor((a.width-w)/2)+(+$('#importX').value||0),Math.floor((a.height-h)/2)+(+$('#importY').value||0),w,h);
 const data=ctx.getImageData(0,0,a.width,a.height),brightness=+$('#importBrightness').value,contrast=+$('#importContrast').value,factor=(100+contrast)/100;
 $('#scaleValue').textContent=$('#importScale').value+'%';$('#brightnessValue').textContent=brightness;$('#contrastValue').textContent=contrast;
 for(let i=0;i<data.data.length;i+=4)for(let k=0;k<3;k++)data.data[i+k]=(data.data[i+k]-128)*factor+128+brightness*2.55;
 const threshold=+$('#binaryThreshold').value;$('#confirmImport').disabled=kind==='binary'&&(!Number.isInteger(threshold)||threshold<0||threshold>255);if($('#confirmImport').disabled)return;
 if(kind==='binary')binaryPixels(data.data,threshold);ctx.putImageData(data,0,0);
 const preview=$('#importPreview');preview.width=a.width;preview.height=a.height;
 if(kind==='reference'){importResult={action:'metadata',reference:{data:c.toDataURL('image/png'),x:0,y:0,width:a.width,height:a.height,opacity:.4}};preview.getContext('2d').drawImage(c,0,0)}
 else{const pixels=quantizeImport(a,importDraft.mode,data.data,kind==='color'&&$('#dither').checked);importResult={action:'frame_pixels',pixels};paintTo(preview,{...a,frames:[{pixels}]},0)}
 $('#importPreviewPanel').hidden=false;
}
for(const id of ['imageImportMode','binaryThreshold','dither','importBrightness','importContrast','importScale','importX','importY'])$('#'+id).oninput=updateImportPreview;
$('#imageImportMode').onchange=updateImportPreview;$('#dither').disabled=true;
$('#cancelImport').onclick=cancelImageImport;
$('#confirmImport').onclick=async()=>{if(!importDraft||!importResult)return;if(selected!==importDraft.id||frame!==importDraft.frame||state.revision!==importDraft.revision){notify('編集状態が変わりました。画像を読み込み直してください',true);return}if(await mutate(importResult))cancelImageImport()};
async function importImage(file){
 if(!file)return;if(file.size>12*1024*1024){notify('画像は12MB以下にしてください',true);return}
 const target=selected,fi=frame,revision=state.revision,a=structuredClone(asset()),m=mode();const reader=new FileReader();reader.onload=()=>{const image=new Image();image.onload=()=>{if(selected!==target||frame!==fi||state.revision!==revision)return;if(image.width*image.height>16000000){notify('画像は1600万画素以下にしてください',true);return}importDraft={image,asset:a,mode:m,id:target,frame:fi,revision};$('#importBrightness').value=0;$('#importContrast').value=0;$('#importScale').value=100;$('#importX').value=0;$('#importY').value=0;updateImportPreview()};image.onerror=()=>notify('画像を読み込めません',true);image.src=reader.result};reader.readAsDataURL(file)
}
$('#imageFile').onchange=e=>importImage(e.target.files[0]);$('#dropZone').ondragover=e=>{e.preventDefault()};$('#dropZone').ondrop=e=>{e.preventDefault();importImage(e.dataTransfer.files[0])};
for(const id of ['refOpacity','refX','refY','refW','refH'])$('#'+id).onchange=()=>{const reference={...asset().reference,opacity:+$('#refOpacity').value/100,x:+$('#refX').value,y:+$('#refY').value,width:+$('#refW').value,height:+$('#refH').value};mutate({action:'metadata',reference})};$('#removeReference').onclick=()=>mutate({action:'metadata',reference:null});
function showTab(tab){$('#outputPanel').open=true;$$('[data-tab]').forEach(b=>b.classList.toggle('active',b.dataset.tab===tab));$$('.tab-panel').forEach(p=>p.hidden=p.id!==tab)}
$$('[data-tab]').forEach(b=>b.onclick=()=>showTab(b.dataset.tab));$('#exportTop').onclick=()=>{showTab('export');$('#export').scrollIntoView({block:'nearest'})};
async function exportData(fmt,text=false){const url=fmt==='report'?`/api/report?asset=${selected}`:`/api/export?asset=${selected}&frame=${frame}&format=${fmt}`;try{const r=await fetch(url);if(!r.ok)throw new Error((await r.json()).error);if(text){$('#outputText').value=await r.text();showTab('export')}else download(await r.arrayBuffer(),'msx-'+asset().mode+'-f'+(frame+1)+'.'+(fmt==='sheet'?'png':fmt),r.headers.get('Content-Type'))}catch(e){notify(e.message,true)}}
$$('[data-export]').forEach(b=>b.onclick=()=>exportData(b.dataset.export));$$('[data-text]').forEach(b=>b.onclick=()=>exportData(b.dataset.text,true));$('#copyText').onclick=async()=>{try{await navigator.clipboard.writeText($('#outputText').value);notify('テキストをコピーしました')}catch{$('#outputText').select();notify('テキストを選択しました。Ctrl+Cでコピーしてください')}};
$('#saveProject').onclick=()=>{download(JSON.stringify(state.project,null,2),'project.msxpix.json');notify('プロジェクトを書き出しました')};$('#openProject').onclick=()=>$('#projectFile').click();$('#projectFile').onchange=async e=>{const file=e.target.files[0];if(!file)return;try{if(file.size>64*1024*1024)throw new Error('プロジェクトは64MB以下にしてください');const project=JSON.parse(await file.text());if(confirm('現在のプロジェクトを読み込んだファイルに置き換えます。「戻す」で復元できます。'))await mutate({action:'replace',project})}catch(err){notify(err.message,true)}e.target.value=''};
function populateModes(){const chip=$('#newChip').value;$('#newMode').replaceChildren();for(const m of catalog.modes.filter(m=>m.chips.includes(chip))){const o=document.createElement('option');o.value=m.id;o.textContent=m.label;$('#newMode').append(o)}$('#newMode').value=chip==='V9990'?'p1':'screen2';setModeSize()}
function setModeSize(){const m=catalog.modes.find(m=>m.id===$('#newMode').value);$('#newForm').elements.width.value=m.width;$('#newForm').elements.height.value=m.height;$('#newModeNote').textContent=m.note}
$('#newAsset').onclick=()=>$('#newDialog').showModal();$('#emptyCreate').onclick=()=>$('#newDialog').showModal();$('#newChip').onchange=populateModes;$('#newMode').onchange=setModeSize;$('#modeSize').onclick=setModeSize;$$('[data-size]').forEach(b=>b.onclick=()=>{const [w,h]=b.dataset.size.split(',');$('#newForm').elements.width.value=w;$('#newForm').elements.height.value=h});$('#newForm').onsubmit=async e=>{e.preventDefault();const f=$('#newForm').elements;if(await mutate({action:'create',chip:f.chip.value,mode:f.mode.value,name:f.name.value,width:+f.width.value,height:+f.height.value})){frame=0;$('#newDialog').close();selectAsset(selected)}};$$('[data-close]').forEach(b=>b.onclick=()=>$('#'+b.dataset.close).close());$('#help').onclick=()=>$('#helpDialog').showModal();
document.addEventListener('keydown',e=>{if((e.ctrlKey||e.metaKey)&&e.key.toLowerCase()==='s'){e.preventDefault();$('#saveProject').click();return}if(['INPUT','TEXTAREA','SELECT'].includes(document.activeElement.tagName)||$('dialog[open]')||pending||drawing)return;if(e.ctrlKey||e.metaKey){if(e.key.toLowerCase()==='z'){e.preventDefault();mutate({action:e.shiftKey?'redo':'undo'})}if(e.key.toLowerCase()==='y'){e.preventDefault();mutate({action:'redo'})}return}const t={b:'pencil',e:'eraser',f:'fill',l:'line',r:'rect',i:'picker'}[e.key.toLowerCase()];if(t)setTool(t)});
async function init(){try{const session=await api('/api/session');token=session.token;catalog=await api('/api/modes');state=await api('/api/state');for(const chip of ['TMS9918A']){const o=document.createElement('option');o.textContent=chip;$('#newChip').append(o)}populateModes();selected=visibleAssets()[0]?.id;if(selected)selectAsset(selected);else render();setInterval(async()=>{if(pending||drawing||tileDrag||document.activeElement.matches('input,textarea,select')||$('dialog[open]'))return;try{const requestedRev=state.revision;const next=await api('/api/state?since='+requestedRev);if(pending||drawing||tileDrag||state.revision!==requestedRev||document.activeElement.matches('input,textarea,select'))return;if(!next.unchanged){stopPlay();state=next;render();notify('外部の編集を反映しました')}}catch{$('#connection').textContent='接続を再確認中…'}},1800)}catch(e){notify('起動エラー: '+e.message,true);$('#connection').textContent='OFFLINE'}}
$('#paletteEdit').onchange=()=>{const a=asset(),bits=['V9968','V9990'].includes(a.chip)?31:7,hex=$('#paletteEdit').value;const palette=[...a.palette];palette[paletteEditIndex]='#'+[1,3,5].map(i=>Math.round(Math.round(parseInt(hex.slice(i,i+2),16)*bits/255)*255/bits).toString(16).padStart(2,'0')).join('');mutate({action:'metadata',palette})};
$('#tileFocus').onchange=()=>{$('#stampActive').checked=false;fitCanvas()};$('#tileNumber').onchange=draw;
$('#prevTile').onclick=()=>{$('#tileNumber').value=Math.max(0,+$('#tileNumber').value-1);draw()};$('#nextTile').onclick=()=>{$('#tileNumber').value=Math.min(+$('#tileNumber').max,+$('#tileNumber').value+1);draw()};
$('#copyRegion').onclick=()=>{const a=asset(),v=view();regionClipboard={...v,mode:a.mode,chip:a.chip,palette:JSON.stringify(a.palette),pixels:[]};for(let y=0;y<v.height;y++)for(let x=0;x<v.width;x++)regionClipboard.pixels.push(a.frames[frame].pixels[(v.y+y)*a.width+v.x+x]);notify('表示中の領域をコピーしました')};
$('#pasteRegion').onclick=()=>{if(!regionClipboard)return notify('先に領域をコピーしてください',true);const a=asset(),v=view(),r=regionClipboard;if(r.mode!==a.mode||r.chip!==a.chip||r.palette!==JSON.stringify(a.palette))return notify('同じVDP・モード・パレットの素材に貼り付けてください',true);const points=[];for(let y=0;y<Math.min(v.height,r.height);y++)for(let x=0;x<Math.min(v.width,r.width);x++)points.push({x:v.x+x,y:v.y+y,color:r.pixels[y*r.width+x]});mutate({action:'pixels',points})};
// Mode-specific workspaces. All edits still use the revision-checked mutation API.
function colorGroups(a,m,ti,fi){
 const tw=m.encoding==='text'?6:8,cols=Math.ceil(a.width/tw),tx=ti%cols*tw,ty=Math.floor(ti/cols)*8,p=a.frames[fi].pixels;
 const rect=(x,y,w,h)=>{const out=[];for(let yy=y;yy<Math.min(y+h,a.height);yy++)for(let xx=x;xx<Math.min(x+w,a.width);xx++)out.push(yy*a.width+xx);return out};
 let groups=[];
 if(m.encoding==='text')groups=[{label:'全字形共通',indices:rect(0,0,a.width,a.height)}];
 if(m.encoding==='g1'){const start=Math.floor(ti/8)*8,indices=[];for(let t=start;t<Math.min(start+8,cols*Math.ceil(a.height/8));t++)indices.push(...rect(t%cols*8,Math.floor(t/cols)*8,8,8));groups=[{label:`文字 ${start}–${Math.min(start+7,cols*Math.ceil(a.height/8)-1)}`,indices}]}
 if(m.encoding==='g2')groups=Array.from({length:8},(_,y)=>({label:`行 ${y}`,indices:rect(tx,ty+y,8,1)}));
 if(m.encoding==='sp1')groups=[{label:'全体の表示色',indices:rect(0,0,a.width,a.height)}];
 if(m.encoding==='sp2')groups=Array.from({length:a.height},(_,y)=>({label:`行 ${y}`,indices:rect(0,y,a.width,1)}));
 return groups.map(g=>({...g,colors:[...new Set(g.indices.map(i=>p[i]).filter(v=>m.kind!=='sprite'||v!==0))].sort((a,b)=>a-b)}));
}
function tileSwapPoints(a,tw,from,to,fi,copyOnly=false){
 const cols=a.width/tw,total=cols*(a.height/8);
 if(!Number.isInteger(cols)||!Number.isInteger(total)||![from,to].every(t=>Number.isInteger(t)&&t>=0&&t<total))throw new Error('部品番号が範囲外です');
 if(from===to)return [];
 const p=a.frames[fi].pixels,points=[];
 for(let y=0;y<8;y++)for(let x=0;x<tw;x++){
  const sx=from%cols*tw+x,sy=Math.floor(from/cols)*8+y,dx=to%cols*tw+x,dy=Math.floor(to/cols)*8+y;
  points.push({x:dx,y:dy,color:p[sy*a.width+sx]});
  if(!copyOnly)points.push({x:sx,y:sy,color:p[dy*a.width+dx]});
 }
 return points;
}
function clearTileDrag(){tileDrag=null;$$('.tile-choice').forEach(b=>b.classList.remove('drag-source','drop-target'))}
function bindTileDrag(button,t){
 button.draggable=true;button.dataset.tile=String(t);button.title=`部品 ${t} · ドラッグで交換 / Ctrl＋ドラッグでコピー（現在のフレーム）`;
 button.ondragstart=e=>{if(pending||drawing){e.preventDefault();return}stopPlay();tileDrag={tile:t,assetId:selected,frame,revision:state.revision};e.dataTransfer.effectAllowed='copyMove';e.dataTransfer.setData('text/plain',`9918-tile:${t}`);button.classList.add('drag-source')};
 button.ondragover=e=>{if(!tileDrag||pending)return;e.preventDefault();e.dataTransfer.dropEffect=e.ctrlKey?'copy':'move';button.classList.add('drop-target')};
 button.ondragleave=()=>button.classList.remove('drop-target');
 button.ondragend=clearTileDrag;
 button.ondrop=async e=>{if(!tileDrag)return;e.preventDefault();e.stopPropagation();const source=tileDrag,copyOnly=e.ctrlKey;clearTileDrag();if(pending||drawing)return;if(source.assetId!==selected||source.frame!==frame||source.revision!==state.revision)return notify('編集状態が変わりました。もう一度ドラッグしてください。',true);const points=tileSwapPoints(asset(),mode().encoding==='text'?6:8,source.tile,t,frame,copyOnly);if(!points.length)return;if(await mutate({action:'pixels',points})){$('#tileNumber').value=t;$('#tileFocus').checked=true;$('#stampActive').checked=false;modeWorkspace();fitCanvas();notify(copyOnly?`部品 ${source.tile} を ${t} にコピーしました。元の部品は残っています。`:`部品 ${source.tile} と ${t} を交換しました（現在のフレーム）。「戻す」で取消できます。`)}};
}
function modeWorkspace(){
 const a=asset(),m=mode(),enc=m.encoding,char=m.kind==='character',sprite=m.kind==='sprite';
 document.body.dataset.workspace=m.kind;$('#editSize').hidden=!char;$('#zoom').hidden=char;for(const o of $('#editSize').options){const n=+o.value;o.textContent=`${enc==='text'?n/8*6:n}×${n}編集`}$('#partsLibrary').hidden=false;$('#editPart').hidden=!char;$('#editWhole').hidden=!char;$('#editPart').classList.toggle('active',char&&$('#tileFocus').checked);$('#editWhole').classList.toggle('active',char&&!$('#tileFocus').checked&&!$('#stampActive').checked);
 $('#modeWorkspaceTitle').textContent=enc==='text'?'6×8 フォント編集':enc==='g1'?'SCREEN 1 · 8文字共有カラー':enc==='g2'?'8×8 パターン · 行別カラー':enc==='tile4'?'V9990 · 4bpp タイル編集':sprite?'スプライト · 透明色とアニメーション':enc==='mc'?'MULTICOLOR · 4×4ブロック編集':direct()?'直接色ビットマップ編集':'パレットビットマップ編集';
 $('#modeWorkspaceNote').textContent=m.note;
 for(const el of $$('.tile-bar > label,.tile-bar > #prevTile,.tile-bar > #nextTile,.tile-bar > #tileTotal'))el.hidden=!char;
 $('#tileInfo').hidden=!char;
 $('#stampBar').hidden=!char;$('#stampActive').disabled=!stampCompatible();if(!stampCompatible())$('#stampActive').checked=false;$('#newStampCanvas').disabled=!stamp;const placing=char&&$('#stampActive').checked;$('#partsLibrary').hidden=false;$('#tileAtlas').hidden=!char;$('#overviewGridLabel').hidden=!char;$('#modeColors').hidden=placing;if(placing)$('#modeWorkspaceTitle').textContent='スタンプ配置 · マスをクリックして部品を配置';
 $('#timelineLabel').textContent=sprite?'アニメーション':char?'字形セット / フレーム':'画像 / フレーム';
 $('#modeColors').replaceChildren();
 $('#tileAtlas').replaceChildren();
 if(char){const tw=enc==='text'?6:8,cols=a.width/tw,total=cols*(a.height/8),ti=+$('#tileNumber').value||0;for(let t=0;t<total;t++){const b=document.createElement('button');b.className='tile-choice'+(t===ti?' active':'');b.setAttribute('aria-label',`文字選択 ${t}`);bindTileDrag(b,t);b.onclick=()=>{$('#tileNumber').value=t;$('#tileFocus').checked=true;$('#stampActive').checked=false;modeWorkspace();fitCanvas()};$('#tileAtlas').append(b)}}
 overviewLayout();
 const groups=colorGroups(a,m,+$('#tileNumber').value||0,frame);
 if(groups.length){const note=document.createElement('p');note.textContent=sprite?'色0は透明。色を変更すると、その行／全体の表示ドットを置換します。':'左＝低い色番号、右＝高い色番号。選択範囲の既存色を置換します（現在のフレーム）。';$('#modeColors').append(note)}
 for(const g of groups){const row=document.createElement('div');row.className='mode-color-row';const label=document.createElement('span');label.textContent=g.label;row.append(label);const limit=sprite?1:2;if(g.colors.length>limit){const warning=document.createElement('strong');warning.textContent=`${g.colors.length}色：制約超過`;row.append(warning)}else for(let slot=0;slot<limit;slot++){const old=g.colors[slot];const select=document.createElement('select');select.setAttribute('aria-label',`${g.label} ${sprite?'表示色':slot?'色B':'色A'}`);if(old===undefined){const o=new Option('未使用','');select.append(o)}for(let n=sprite?1:0;n<a.palette.length;n++)select.append(new Option(`${n} ${a.palette[n]}`,String(n)));select.value=old===undefined?'':String(old);select.onchange=async()=>{if(select.value==='')return;const next=+select.value;color=next;renderPalette();if(old===undefined){notify('描画色に設定しました。ドットを描くと色が割り当てられます。');return}const pixels=[...asset().frames[frame].pixels];for(const i of g.indices)if(pixels[i]===old)pixels[i]=next;await mutate({action:'frame_pixels',pixels})};row.append(select)}$('#modeColors').append(row)}
 $('#bitmapControls').hidden=char||sprite;
 $('#pixelFormat').textContent=`${a.width} × ${a.height} / ${enc.toUpperCase()}${enc==='mc'?' / 1画素＝表示4×4ドット':''}`;
 $('#encodedPreview').hidden=!['yjk','yjae','yuv','yuae'].includes(enc);
 $('#encodedImage').hidden=true;$('#encodedImage').removeAttribute('src');
 $('#directControls').hidden=!direct();
 if(direct())for(const [id,shift] of [['red5',5],['green5',10],['blue5',0]])$('#'+id).value=(color>>shift)&31;
 $('#bankControls').hidden=!/^b[4-7]_/.test(a.mode);
 if(!$('#bankControls').hidden)$('#bankNote').textContent=`偶数X: 0–${a.palette.length/2-1} / 奇数X: ${a.palette.length/2}–${a.palette.length-1}。描画する列に対応する色を選択。`;
}
function overviewLayout(){
 const a=asset();if(!a)return;const automatic=$('#overviewScale').value==='fit',tw=mode().encoding==='text'?6:8;
 const viewerHeight=Math.max(430,Math.min(552,window.innerHeight-$('#canvasWrap').getBoundingClientRect().top-180));
 document.documentElement.style.setProperty('--viewer-height',viewerHeight+'px');
 const viewport=$('#overviewViewport'),availableHeight=viewerHeight;
 viewport.style.maxHeight=availableHeight+'px';
 const scale=automatic?Math.min(Math.max(1,viewport.clientWidth-2)/a.width,Math.max(1,availableHeight-2)/a.height):+$('#overviewScale').value;
 $('#overviewImage').style.width=a.width*scale+'px';$('#overviewImage').style.height=a.height*scale+'px';
 $('#preview').style.width=a.width*scale+'px';$('#preview').style.height=a.height*scale+'px';
 $('#tileAtlas').style.gridTemplateColumns=`repeat(${a.width/tw}, ${tw*scale}px)`;$('#tileAtlas').style.gridAutoRows=8*scale+'px';
 $('#tileAtlas').classList.toggle('with-grid',$('#overviewGrid').checked);
 const v=view(),outline=$('#overviewSelection');outline.hidden=!($('#tileFocus').checked&&mode().kind==='character');Object.assign(outline.style,{left:v.x*scale+'px',top:v.y*scale+'px',width:v.width*scale+'px',height:v.height*scale+'px'});

}
window.addEventListener('resize',()=>{if(asset())overviewLayout()});
$('#overviewScale').onchange=()=>{overviewLayout();if(asset())fitCanvas()};$('#overviewGrid').onchange=overviewLayout;

function stampCompatible(){const a=asset();return !!stamp&&stamp.mode===a.mode&&stamp.chip===a.chip&&stamp.palette===JSON.stringify(a.palette)}
function captureStamp(){const a=asset(),tw=mode().encoding==='text'?6:8,ti=+$('#tileNumber').value||0,cols=Math.ceil(a.width/tw),x=ti%cols*tw,y=Math.floor(ti/cols)*8;stamp={mode:a.mode,chip:a.chip,palette:JSON.stringify(a.palette),width:tw,pixels:[],name:`${a.name} / 文字 ${ti}`};for(let yy=0;yy<8;yy++)for(let xx=0;xx<tw;xx++)stamp.pixels.push(a.frames[frame].pixels[(y+yy)*a.width+x+xx]);const c=$('#stampPreview');c.width=tw;c.height=8;c.getContext('2d').drawImage(thumb(a,frame),x,y,tw,8,0,0,tw,8);$('#stampName').textContent=stamp.name;$('#stampActive').disabled=false;$('#stampActive').checked=true;$('#tileFocus').checked=false;modeWorkspace();fitCanvas();notify('スタンプを取り込みました。配置画面のマスをクリックしてください。')}
function placeStamp(pos,erase=false){if(!stampCompatible())return;const a=asset(),x=Math.floor(pos.x/stamp.width)*stamp.width,y=Math.floor(pos.y/8)*8,points=[];for(let yy=0;yy<8;yy++)for(let xx=0;xx<stamp.width;xx++)if(x+xx<a.width&&y+yy<a.height)points.push({x:x+xx,y:y+yy,color:erase?0:stamp.pixels[yy*stamp.width+xx]});mutate({action:'pixels',points})}
$('#captureStamp').onclick=captureStamp;
$('#stampActive').onchange=()=>{if($('#stampActive').checked)$('#tileFocus').checked=false;else $('#tileFocus').checked=true;modeWorkspace();fitCanvas()};
$('#newStampCanvas').onclick=async()=>{if(!stamp)return;const source=stamp;const w=source.width===6?96:128;if(await mutate({action:'create',chip:source.chip,mode:source.mode,name:'スタンプ配置 / '+source.name,width:w,height:128})){await mutate({action:'metadata',palette:JSON.parse(source.palette)});frame=0;$('#tileFocus').checked=false;$('#stampActive').checked=true;modeWorkspace();fitCanvas()}};
const originalRender=render;render=function(){originalRender();if(asset())modeWorkspace()};
const originalPalette=renderPalette;renderPalette=function(){originalPalette();if(direct())for(const [id,shift] of [['red5',5],['green5',10],['blue5',0]])$('#'+id).value=(color>>shift)&31};
const originalFrames=renderFrames;renderFrames=function(){originalFrames();if(state&&catalog&&asset())modeWorkspace()};
const originalSelect=selectAsset;selectAsset=function(id){$('#stampActive').checked=false;originalSelect(id);if(!pending&&!drawing&&asset()){$('#tileFocus').checked=mode().kind==='character';modeWorkspace();fitCanvas()}};
for(const id of ['tileNumber','tileFocus']){const previous=$('#'+id).onchange;$('#'+id).onchange=()=>{previous();modeWorkspace()}}
for(const id of ['prevTile','nextTile']){const previous=$('#'+id).onclick;$('#'+id).onclick=()=>{previous();modeWorkspace()}}
for(const id of ['red5','green5','blue5'])$('#'+id).onchange=()=>{for(const field of ['red5','green5','blue5'])$('#'+field).value=Math.max(0,Math.min(31,Math.round(+$('#'+field).value)||0));color=(+$('#green5').value<<10)|(+$('#red5').value<<5)|+$('#blue5').value;renderPalette()};
$('#encodedPreview').onclick=()=>{const img=$('#encodedImage');img.src=`/api/export?asset=${selected}&frame=${frame}&format=encoded&r=${state.revision}`;img.hidden=false;img.onerror=()=>{img.hidden=true;notify('変換結果を取得できません。検証結果を確認してください。',true)}};
$('#evenBank').onclick=()=>{color=color%(asset().palette.length/2);renderPalette()};$('#oddBank').onclick=()=>{color=color%(asset().palette.length/2)+asset().palette.length/2;renderPalette()};
const originalSize=setModeSize;setModeSize=function(){originalSize();const m=catalog.modes.find(m=>m.id===$('#newMode').value);for(const b of $$('[data-size]')){const [w,h]=b.dataset.size.split(',').map(Number);b.hidden=m.encoding==='text'||m.kind==='graphic'||m.id==='v9sprite'&&w!==16||['sp1','sp2'].includes(m.encoding)&&w>16;b.textContent=w===128?'128×128 タイルセット':`${w}×${h}`}};
$('#editPart').onclick=()=>{$('#tileFocus').checked=true;$('#stampActive').checked=false;modeWorkspace();fitCanvas()};
$('#editWhole').onclick=()=>{$('#tileFocus').checked=false;$('#stampActive').checked=false;modeWorkspace();fitCanvas()};
init();

function drawOverviewReference(a){
 const overlay=$('#overviewReference'),r=a.reference;
 overlay.hidden=!(r&&referenceImage?.complete&&referenceImage.naturalWidth);
 if(overlay.hidden)return;
 if(overlay.getAttribute('src')!==r.data)overlay.src=r.data;
 Object.assign(overlay.style,{left:(r.x/a.width*100)+'%',top:(r.y/a.height*100)+'%',width:(r.width/a.width*100)+'%',height:(r.height/a.height*100)+'%',opacity:r.opacity});
}

let importPan=null;
$('#importPreview').onpointerdown=e=>{if(!importDraft||e.button!==0)return;e.preventDefault();const r=e.currentTarget.getBoundingClientRect();importPan={id:e.pointerId,x:e.clientX,y:e.clientY,ox:+$('#importX').value||0,oy:+$('#importY').value||0,sx:importDraft.asset.width/r.width,sy:importDraft.asset.height/r.height};e.currentTarget.setPointerCapture(e.pointerId)};
$('#importPreview').onpointermove=e=>{if(!importPan||e.pointerId!==importPan.id)return;$('#importX').value=Math.round(importPan.ox+(e.clientX-importPan.x)*importPan.sx);$('#importY').value=Math.round(importPan.oy+(e.clientY-importPan.y)*importPan.sy);updateImportPreview()};
for(const type of ['pointerup','pointercancel'])$('#importPreview').addEventListener(type,e=>{if(!importPan||e.pointerId!==importPan.id)return;if(type==='pointercancel'){$('#importX').value=importPan.ox;$('#importY').value=importPan.oy;updateImportPreview()}importPan=null;if(e.currentTarget.hasPointerCapture(e.pointerId))e.currentTarget.releasePointerCapture(e.pointerId)});
$('#centerImport').onclick=()=>{$('#importX').value=0;$('#importY').value=0;updateImportPreview()};

// Repeat-click restoration belongs only to an uninterrupted pencil session.
function clearRepeatClick(){if(!drawing)togglePixels.clear()}
document.addEventListener('pointerdown',e=>{if(e.target!==canvas)clearRepeatClick()},true);
document.addEventListener('change',clearRepeatClick,true);
document.addEventListener('keydown',clearRepeatClick,true);

function saveEditorPreferences(){try{const values={color,rightColor};for(const id of ['inputMode','editSize','overviewScale'])values[id]=$('#'+id).value;for(const id of ['grid','overviewGrid','onion'])values[id]=$('#'+id).checked;localStorage.setItem('9918-studio-editor-preferences',JSON.stringify(values))}catch{}}
try{const prefs=JSON.parse(localStorage.getItem('9918-studio-editor-preferences')||'{}');for(const id of ['inputMode','editSize','overviewScale'])if([...$('#'+id).options].some(o=>o.value===prefs[id]))$('#'+id).value=prefs[id];for(const id of ['grid','overviewGrid','onion'])if(typeof prefs[id]==='boolean')$('#'+id).checked=prefs[id];if(Number.isInteger(prefs.color)&&prefs.color>=0&&prefs.color<16)color=prefs.color;if(Number.isInteger(prefs.rightColor)&&prefs.rightColor>=0&&prefs.rightColor<16)rightColor=prefs.rightColor;}catch{}
document.addEventListener('change',saveEditorPreferences);
